replicaCount: 2

image:
  repository: sakshineeraj/cicd
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "fake-news-detector"
fullnameOverride: "fake-news-detector"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

configMap:
  enabled: true
  modelPath: /app/nlp_model.pkl
  transformPath: /app/transform.pkl

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "fnd-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: fake-news-detector.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fake-news-detector-tls
      hosts:
        - fake-news-detector.com
