apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fake-news-detector.fullname" . }}
  labels:
    {{- include "fake-news-detector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fake-news-detector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fake-news-detector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fake-news-detector.serviceAccountName" . }}
      securityContext:
        {}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.configMap.enabled }}
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: {{ include "fake-news-detector.fullname" . }}
              key: model-path
        - name: TRANSFORM_PATH
          valueFrom:
            configMapKeyRef:
              name: {{ include "fake-news-detector.fullname" . }}
              key: transform-path
        {{- end }}